version: 1
disable_existing_loggers: false

formatters:
  json:
    class: pythonjsonlogger.json.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(module)s %(funcName)s %(lineno)d %(message)s"

handlers:
  stdout:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: json

loggers:
  app_server_logger:
    level: "INFO"
    handlers:
      - stdout
    propagate: no

root:
  level: "INFO"
  handlers:
    - stdout